### ISSUE TITLE
Incorrect URL parsing

### ISSUE THREAD

**Issue by mhidro** [denorg/humanize-url#2]
The following url is a valid url which is incorrectly rejected with a message "Invalid URL"
`http://username:password@example.com/`

It might not be a good idea to use such a URL, but still it's a valid URL.

Optional trailing dot after TLD also breaks the regex. 
`https://example.com./`

**Comment by yg** [comment]
Thanks for the issue! We'll take your request into consideration and follow up if we decide to tackle this issue.

To claim an issue to work on or need any help, please leave a comment.

**Comment by yg** [comment]
Fixed :tada:

@mhidro Can you check now?

**Comment by mhidro** [comment]
Seems to work fine now.

**Comment by yg** [comment]
Thanks for the feedback @mhidro :purple_heart:
